const path = require('path'); //used to specify the path for the output.

/* Specifies custom names for the entry and output properties. */

module.exports = {
    mode: 'production',
    entry: {
        main: path.resolve(__dirname, './js/dashboard_main.js'), //Webpack custom entry point file.
    },
    output: {
        filename: 'bundle.js', // custom output file that will be generated by webpack.
        path: path.resolve(__dirname, 'public') // The output file will be stored in the 'public' folder.
    },
    performance: {
        hints: true,
        maxAssetSize: 512000,
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ["style-loader", "css-loader"]
            },
            {
                test: /\.png$/,
                use: [
                  'file-loader',
                  {
                    loader: 'image-webpack-loader',
                    options: {
                      bypassOnDebug: true, // webpack@1.x
                      disable: true, // webpack@2.x and newer
                      mozjpeg: {
                        progressive: true,
                      },
                    },
                  },
                ],
              }
        ]
    },
};
