/* Specifies custom names for the entry and output properties. */


const path = require('path'); //used to specify the path for the output.

module.exports = {
    entry: {
        main: path.resolve(__dirname, './js/dashboard_main.js'), //Webpack entry point file.
    },
    output: {
        filename: 'bundle.js', // Output file that will be generated by webpack.
        path: path.resolve(__dirname, 'public') // The output file will be stored in the 'public' folder.
    },
};
