const path = require('path'); //used to specify the path for the output.

/* Specifies custom names for the entry and output properties. */

module.exports = {
    mode: 'production',
    entry: {
        main: path.resolve(__dirname, './js/dashboard_main.js'), //Webpack custom entry point file.
    },
    output: {
        filename: 'bundle.js', // custom output file that will be generated by webpack.
        path: path.resolve(__dirname, 'public') // The output file will be stored in the 'public' folder.
    },
};
